[program:uv-logger]
command=/usr/bin/python /home/pi/sources/pi-geo-station/uv/reader.py
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/uv-logger/uv-logger.err.log
stdout_logfile=/var/log/uv-logger/uv-logger.out.log
user=pi
